# Generated by Django 5.1.6 on 2025-04-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_friendrequest_friend"),
    ]

    operations = []
