# Generated by Django 5.1.6 on 2025-04-12 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_alter_friend_options_alter_friendrequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friend",
            options={},
        ),
        migrations.AlterModelOptions(
            name="friendrequest",
            options={},
        ),
        migrations.AlterModelOptions(
            name="groupchat",
            options={},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="groupchat",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="friend",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="groupchat",
            name="members",
            field=models.ManyToManyField(
                related_name="group_chat", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="groupchat",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Groupmchatmessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "group_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.groupchat",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_group_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GroupMessage",
        ),
        migrations.RemoveField(
            model_name="groupchat",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="groupchat",
            name="creator",
        ),
    ]
