# Generated by Django 5.1.6 on 2025-04-12 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_alter_friend_options_alter_friendrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
