# Generated by Django 5.1.6 on 2025-04-14 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_friend_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupchat",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="groupmchatmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="groupchat",
            name="admin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_groups",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupchat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupchat",
            name="members",
            field=models.ManyToManyField(
                related_name="group_chats", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="groupmchatmessage",
            name="group_chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messaging.groupchat",
            ),
        ),
        migrations.AlterField(
            model_name="groupmchatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
